package com.currency.testcurrency.repository.local.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FAVORITE".
 */
@Entity
public class Favorite {

    @Id(autoincrement = true)
    private Long id;
    private int currency_id;
    private String from;
    private String to;
    private Double rate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Favorite() {
    }

    public Favorite(Long id) {
        this.id = id;
    }

    @Generated
    public Favorite(Long id,  String from, String to, Double rate) {
        this.id = id;
        this.from = from;
        this.to = to;
        this.rate = rate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCurrency_id() {
        return currency_id;
    }

    public void setCurrency_id(int favoriteId) {
        this.currency_id = favoriteId;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public Double getRate() {
        return rate;
    }

    public void setRate(Double rate) {
        this.rate = rate;
    }

}
